#!/usr/bin/env python
'''
This script is used to kick off a bonneville minion daemon
'''

from bonneville.scripts import bonneville_minion
from multiprocessing import freeze_support


if __name__ == '__main__':
    # This handles the bootstrapping code that is included with frozen
    # scripts. It is a no-op on unfrozen code.
    freeze_support()
    bonneville_minion()
